# action.yml
name: 'SDKMAN!'
description: 'Greet someone and record the time'
inputs:
  candidate:  # id of input
    description: 'Who to greet'
    required: true
  version: # id of input
    description: 'Who to greet'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.candidate }}
    - ${{ inputs.version }}
