name: Main workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java 15.0.0-amzn
      id: setup-java
      uses: ./
      with:
        candidate: java
        version: 15.0.0-amzn
    - name: Verify Java 15.0.0-amzn
      run: test/verify-java.sh 15.0.0 "${{ steps.setup-java.outputs.path }}" "${{ steps.setup-java.outputs.version }}"
