name: Main workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java 8.0.265.hs-adpt
      uses: ./
      with:
        candidate: java
        version: 8.0.265.hs-adpt
